title: Wiki dos Laboratórios de Informática
description: Página Wiki dos Laboratórios de Informática do Bloco B do IFB, campus Taguatinga.
# url: localhost:4000
url: https://ifbctag.github.io/labwiki
show_downloads: false
git_branch: master
logo_url: assets/images/ifb-taguatinga.png
google_analytics:
theme: 
wiki_folder: wiki
use_github_wiki: false
use_prose_io: false
google_cse_token: 
custom_head: false
custom_sidebar: false
custom_footer: false
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
